### ISSUE TITLE
Radiobuttons without the label

### ISSUE THREAD

**Issue by sera2007** [ThakurBallary/react-native-radio-buttons-group#10]
Hi, great thanks for your library
I need to use it without the label text, you can check the UI here http://take.ms/SWBDO
Is there any way to hide the label text now? 

I was trying to use label:' ' , but the radios work wrong in this way.

**Comment by Pavaneshpratap** [comment]
label: <Text style={{fontWeight:"bold"}}></Text>

**Comment by ThakurBallary** [comment]
Fixed in [v2.0.0](https://github.com/ThakurBallary/react-native-radio-buttons-group/releases/tag/v2.0)
