### ISSUE TITLE
[ENHANCEMENT] Default Selection based on props

### ISSUE THREAD

**Issue by KashyapProdigy** [ThakurBallary/react-native-radio-buttons-group#16]
Consider I have category state with value either A,B,C intialized by navigation props 

I declared  radio state as per docs with labels and value

I want the initial radio selected as per 

This.state.radio.value == this.state.category

Thanks from future ! 👍

**Comment by KashyapProdigy** [comment]
The daily always seems to be radio[0] the first element of my radio state

**Comment by ThakurBallary** [comment]
Hope you can find a possible solution with [v2.0.0](https://github.com/ThakurBallary/react-native-radio-buttons-group/releases/tag/v2.0) as there are a lots of enhancements made to the package.

If you need help, please share the code snippet or link to example on expo snack would be appreciated.
