### ISSUE TITLE
Bug: updating the radioButtons prop of a RadioGroup component doesn't update its options

### ISSUE THREAD

**Issue by taeh98** [ThakurBallary/react-native-radio-buttons-group#20]
# Bug description

Hello, I hope this finds you well.

I have found that when you pass a new or changed radioButtons prop to a RadioGroup component its options do not update.

Please could you fix this issue? Thank you in advance for your time and effort.

# To reproduce

1. Clone the repo https://github.com/taeh98/react-native-radio-buttons-group-not-updating
2. Install and link the dependencies
3. Run the repo with "expo start"

# Desired and expected behavior

The behaviour that I expected and desired was that when you update the radioButtons prop given to a RadioGroup component, its radio button options would update if they were changed. For example, you should be able to update the label or colour of a RadioButtonProps option in the RadioGroup component.

# Actual behavior

I have found that when you update the radioButtons prop given to a RadioGroup component, its radio button options do not update. Every field of each RadioButtonProps option stays the same apart from the selected option, which appears to update automatically when the selected option changes - so I assume that this too cannot be changed manually.

# Environment info

For package versions etc, see https://github.com/taeh98/react-native-radio-buttons-group-not-updating/blob/main/package.json

**Comment by ThakurBallary** [comment]
@taeh98 Thank you for pointing the issue. 

Released an update with the fix.

Output after fix:
[Snack Link](https://snack.expo.io/@thakurballary/radio-buttons-prop-update-issue)
