### ISSUE TITLE
Check the render method of RadioButton

### ISSUE THREAD

**Issue by amdrade** [ThakurBallary/react-native-radio-buttons-group#25]
Error when reproducing basic example of the documentation.
![WhatsApp Image 2021-05-22 at 23 03 53](https://user-images.githubusercontent.com/5581309/119245811-6750e800-bb52-11eb-9a95-5ea47f2e1b71.jpeg)

**Comment by ThakurBallary** [comment]
Here is the [Snack link](https://snack.expo.io/@thakurballary/react-native-radio-buttons-group-example) of basic example from documentation.

If it's still not working for you. Can you please share your code snippet?

**Comment by morelgarisi** [comment]
> 

see if you are on a react version that support the pressable if not change to touchable
