### ISSUE TITLE
Setting a selected option with UseEffect doesn't work

### ISSUE THREAD

**Issue by JerryBels** [ThakurBallary/react-native-radio-buttons-group#28]
Hello,

Here is a snack to show the issue.

https://snack.expo.dev/@jerrybels/react-native-radio-buttons-group-example

Selecting one of the options in `useEffect` doesn't work as expected - the option isn't selected. I found out that it is selected if the state is initialized with an empty array :

```
const [radioButtons, setRadioButtons] = useState([]);
```

I don't really understand why. It's like the state is initialized after the effect took place? But then why aren't the options disappearing? 

Thanks ahead.

**Comment by ThakurBallary** [comment]
Hi @JerryBels 

In the above snack example, radioButtonsData has changed but reference is same, due to which the react doesn't render. One of the way to update the reference is to use spread operator (...)

replace

```
setRadioButtons(radioButtonsData);
```

with 

```
setRadioButtons([...radioButtonsData]);
```
I hope this was helpful. 
Thanks

**Comment by JerryBels** [comment]
Thank you @ThakurBallary it was really helpful, and thanks for the great module :)
