### ISSUE TITLE
How to get the selected button value?

### ISSUE THREAD

**Issue by AleenWael** [ThakurBallary/react-native-radio-buttons-group#30]

**Comment by ThakurBallary** [comment]
There are multiple ways to get the selected value. One of the way is, using **find** method on array.

**Comment by RowlandOti** [comment]
The action/function is never called on pressing a RadioButton i.e `onPress: toggleRadio`  - toggleRadio(id: string) is never invoked. Why? What is the behaviour of onPress()

**Comment by ThakurBallary** [comment]
onPress function is invoked and updated state of radio buttons is passed to caller function.
Please find the link to working example in
https://github.com/ThakurBallary/react-native-radio-buttons-group/issues/25#issuecomment-846493544

**Comment by RowlandOti** [comment]
there are two onPress, one for RadioGroup and another for RadioButton. I am speaking about one for RadioButton. It's never invoked. Can you give sample usage in the example shared?

**Comment by victor47n** [comment]
> there are two onPress, one for RadioGroup and another for RadioButton. I am speaking about one for RadioButton. It's never invoked. Can you give sample usage in the example shared?

I suffer from the same problem, when using the RadioButton's OnPress(), it is never invoked.

An example:
`{
  id: '1',
  label: 'Test',
   value: '',
  borderColor: theme.colors.primary,
  color: theme.colors.primary,
  onPress: () => {
  console.log('Press?')
}`

**Comment by RowlandOti** [comment]
@ThakurBallary your example uses the onPress passed to RadioGroup. We are referring to the one passed to a single RadioButton. Can you kindly adjust your example with that uses case to show how to use the RadioButtons onPress(), or otherwise let us know if is faulty, so we may know how to help if possible.

**Comment by ThakurBallary** [comment]
@RowlandOti @victor47n Thanks for writing.
Sorry, it took some time for me to understand. @victor47n example has helped me to understand the issue.
Release v2.2.7 with the fix. [Working example on Snack](https://snack.expo.dev/@thakurballary/invoke-radiobutton-onpress)

**Comment by RowlandOti** [comment]
Thanks for the quick fix, I can confirm this works now.

**Comment by victor47n** [comment]
@ThakurBallary Thanks for the quick fix!

**Comment by brunozn** [comment]
Para pegar o value fiz assim:                  
  ```onPress={(selectedId) => {
                      const selectedItem = radioButtons.find(item => item.id === selectedId);
                      console.log('selectedItem', selectedItem);

                      if (selectedItem) {
                        setSelectedId(selectedItem.id);
                        onChange(selectedItem.value);
                      }
                    }}
```
