### ISSUE TITLE
Circular Dependency Warning

### ISSUE THREAD

**Issue by RowlandOti** [ThakurBallary/react-native-radio-buttons-group#33]
Circular dependency warning when using the library. I get the following error on the react native app am using this on:

>` WARN     Require cycle: node_modules\react-native-radio-buttons-group\lib\index.ts -> node_modules\react-native-radio-buttons-group\lib\RadioGroup.tsx -> node_modules\react-native-radio-buttons-group\lib\index.ts`

As this is an error occurring in the library, it needs to be fixed at the source.

**Comment by ThakurBallary** [comment]
@RowlandOti thanks for writing. Fixed and released v2.2.6
