### ISSUE TITLE
when setting state in onpress the inner circle does not show- the selected one

### ISSUE THREAD

**Issue by morelgarisi** [ThakurBallary/react-native-radio-buttons-group#34]
<Common.RadioGroup
              radioButtons={[
                {
                  id: '1',
                  label: 'אופציה 1',
                  value: 'option1',
                  color: 'blue',
                  layout: 'row',
                  size: 24,
                },
                {
                  id: '2',
                  label: 'אופציה 2',
                  value: 'option2',
                  layout: 'row',
                  size: 26,
                },
              ]}
              layout={'row'}
              onPress={arr=> {
                console.log('pressed group')
                let sel=arr.find(e => e.selected)?.value
                this.setState({radio_selected:sel})
            }}
              containerStyle={{ backgroundColor: 'yellow' }}
            />

**Comment by morelgarisi** [comment]
whats the point of this line :
  if (!_.isEqual(radioButtons, radioButtonsLocal)) {
     setRadioButtonsLocal(radioButtons);
   }
by removing it everything  works

**Comment by ThakurBallary** [comment]
#30 helps you understand the use and you can also find working example over there.
