### ISSUE TITLE
Don't import the whole lodash library

### ISSUE THREAD

**Issue by Hirbod** [ThakurBallary/react-native-radio-buttons-group#35]
You are importing the whole lodash library for a single function. This is a terrible pattern and will bloat the bundle, since there is no tree shaking at all.

If you just need isEqual, please use it like this:
```bash
npm install --save lodash.isequal
# or
yarn add lodash.isequal
```

and import 

```tsx
import isEqual from 'lodash.isequal';
```

**Comment by ThakurBallary** [comment]
@Hirbod thanks for writing. Release [v2.2.8](https://github.com/ThakurBallary/react-native-radio-buttons-group/releases/tag/v2.2.8) with the changes you mentioned above.
