### ISSUE TITLE
Styling the radio group?

### ISSUE THREAD

**Issue by zeeshan-shabbir** [ThakurBallary/react-native-radio-buttons-group#37]
i am try to style radio buttons,circle but nothing change i read doc and example but there is no example with styling. i am using this 
` color="#ffffff"
              containerStyle={{ color:"	#FFFFFF" }}
              labelStyle={{ color:"	#FFFFFF" }}`

**Comment by ThakurBallary** [comment]
[Link to working example](https://snack.expo.dev/@thakurballary/rnrbg37)
I hope this is what you're looking for.
