### ISSUE TITLE
radio group can not set label text color

### ISSUE THREAD

**Issue by fukemy** [ThakurBallary/react-native-radio-buttons-group#42]
as image below:

![Screen Shot 2022-07-12 at 14 42 02](https://user-images.githubusercontent.com/8202437/178436655-962d096e-484a-4e4b-8361-de52566b40d0.png)

![Screen Shot 2022-07-12 at 14 43 55](https://user-images.githubusercontent.com/8202437/178436759-a85c7e2c-15dc-4a1d-80d4-4256e93ef5dd.png)

**Comment by ThakurBallary** [comment]
@fukemy pass **labelStyle** from **radioButtons**
Example: `const radioButtons = [{ label: Option 1, labelStyle: { color: 'red' }}]`
