### ISSUE TITLE
How to Change borderColor

### ISSUE THREAD

**Issue by muzz56** [ThakurBallary/react-native-radio-buttons-group#46]
Hi, 
I'm not able to change borderColor of the radio buttons. Can you please guide me on how to change it?
Below is my code: 

 `<RadioGroup
            radioButtons={radioButtons}
            onPress={onPressRadioButton}
            containerStyle={{alignSelf: 'flex-start'}}
            borderColor={'#E6A4AA'} 
          />`

**Comment by ThakurBallary** [comment]
We have to pass `borderColor` property to `radioButton`. Here is the working [snack example](https://snack.expo.dev/@thakurballary/rnrbg46)

**Comment by muzz56** [comment]
Okay. So if I have 5 radio buttons, I want the same borderColor for all. Do i have to write 5 times in every object?

**Comment by ThakurBallary** [comment]
Yes, you can run a loop for that. It's written in this way to have the flexibility to customize individual radio buttons. The thought process is that usually there will be very few radio buttons used.
