### ISSUE TITLE
Background image in Label

### ISSUE THREAD

**Issue by franky358** [ThakurBallary/react-native-radio-buttons-group#47]
Hi there. Is there a way to set a background image for the radio button labels? I tried with labelStyle with no positive results. Any way to use <Image Background> or <Image> component?

**Comment by ThakurBallary** [comment]
This package doesn't support background image for label at the moment. PRs are welcome from open source contributors. Thanks!!

**Comment by franky358** [comment]
All right, thanks for the awesome package!

**Comment by ThakurBallary** [comment]
I gave it a try and was able to achieve it. You can connect with me on [LinkedIn](https://linkedin.com/in/thakurballary) to discuss this further.
