### ISSUE TITLE
RadioGroup How to change Style Radio Button and Text label

### ISSUE THREAD

**Issue by khanhdevvn** [ThakurBallary/react-native-radio-buttons-group#48]
RadioGroup How to change Style Radio Button and Text label

**Comment by ThakurBallary** [comment]
Here is the [Snack Example](https://snack.expo.dev/@thakurballary/rnbg48).
Thanks!!

**Comment by ThakurBallary** [comment]
@khanhdevvn can you share a sample design of your expectation? You might be looking for a checkbox component.
