### ISSUE TITLE
text color is not getting apply

### ISSUE THREAD

**Issue by KrushnaNaghate** [ThakurBallary/react-native-radio-buttons-group#49]
<RadioGroup
                labelStyle={{color: this.context.basicFontColor,}}
                containerStyle={{
                  alignItems: 'flex-start',
                  color: this.context.basicFontColor,
                  backgroundColor:this.context.surfaceColor == '#1A1D21' ? '#2c2c2c' : this.context.surfaceColor
                }}
                descriptionStyle={{color: this.context.basicFontColor}}
                textColor={{color: this.context.basicFontColor}}
                color={this.context.basicFontColor}
                selected={true}
                radioButtons={viewButtonsData}
                onPress={this.selectReqMethod}
              />

**Comment by ThakurBallary** [comment]
Here is the [Snack Example](https://snack.expo.dev/@thakurballary/rnbg48).
Thanks!!
