### ISSUE TITLE
Add support to add custom styles

### ISSUE THREAD

**Issue by saggiyogesh** [ThakurBallary/react-native-radio-buttons-group#5]
Can't give custom styles to the container. In my case Radios are not taking full space. So to do I have to provide custom styles like `width: '100%', flexDirection: 'space-around'`, which is not possible.

**Comment by ThakurBallary** [comment]
NOTE: This package is updated and actively maintained in [react-native-btr](https://npmjs.com/package/react-native-btr) library.
