### ISSUE TITLE
Typescript issue with lodash function

### ISSUE THREAD

**Issue by azuken** [ThakurBallary/react-native-radio-buttons-group#50]
Since I bumped to RN 0.71.0, I've changed some eslint rules, and I have a Typescript error from this lib, which says that a declaration file is missing for `'lodash.isequal'`, in `RadioGroup.tsx` file.

Can it be fixed ?

Here is the full description : 

```
TS7016: Could not find a declaration file for module 'lodash.isequal'. '/Users/xxxx/node_modules/lodash.isequal/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash.isequal` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.isequal';`
```

**Comment by papidb** [comment]
Run `yarn add -D @types/lodash.isequal` to remove the error.

**Comment by azuken** [comment]
It is not a good solution. I do not want to add a peer dependency from this package explicitly, it must be added to this package dependencies.

**Comment by ThakurBallary** [comment]
@azuken @papidb thanks for writing!! 
Added `@types/lodash.isequal` in devDependencies

**Comment by DavidGonzalezGutierrez** [comment]
Sorry but you put @types/lodash-isequal instead of @types/lodash.isequal in dev dependencies.

**Comment by ThakurBallary** [comment]
Updated. thank you @DavidGonzalezGutierrez
