### ISSUE TITLE
multi select

### ISSUE THREAD

**Issue by fukemy** [ThakurBallary/react-native-radio-buttons-group#51]
Hi, thanks for great library.
I want to allow multi select, how can I do it? Thanks so much

**Comment by ThakurBallary** [comment]
`When should you use radio buttons or checkboxes? This relies entirely on what question you are asking. If you want your users to select multiple options, use checkboxes. If you want your users to select only one option, use radio buttons (or another alternative).`

Thank you

**Comment by fukemy** [comment]
yes, I done it, thanks so much
