### ISSUE TITLE
borderColor and color props not working

### ISSUE THREAD

**Issue by savancodexive** [ThakurBallary/react-native-radio-buttons-group#56]
@ThakurBallary Please add this.
When we use RadioGroup Something like as below then not worked due to props passing issue.
![image](https://github.com/ThakurBallary/react-native-radio-buttons-group/assets/85383682/bfafa1c4-7970-4969-8638-0b6b97ad7ea4)

You can fixed by adding this. Please add and give new update
![image](https://github.com/ThakurBallary/react-native-radio-buttons-group/assets/85383682/0b122d62-e979-4dc2-bcba-bc5ccee74abc)

**Comment by ThakurBallary** [comment]
@savancodexive this is similar to #48
