### ISSUE TITLE
Outer circle has some gliches (doesn't have smooth appearance)

### ISSUE THREAD

**Issue by bbeckk** [ThakurBallary/react-native-radio-buttons-group#6]
The outer circle when the btn is selected or not doesn't have smooth circle. Please see the inner circle of the selected radio btn (value is different labelled btn in the image below) which looks very smooth in appearance.

![screenshot_20180831-131152](https://user-images.githubusercontent.com/13558880/44898935-1a80af80-ad20-11e8-8006-d130e12ea0d2.png)

**Comment by ThakurBallary** [comment]
Fixed in [v2.0.0](https://github.com/ThakurBallary/react-native-radio-buttons-group/releases/tag/v2.0)
