### ISSUE TITLE
Touch area is too small or unconfortable.

### ISSUE THREAD

**Issue by halid96** [ThakurBallary/react-native-radio-buttons-group#66]
When it comes to mobile app design, the radio button touch area shall be bigger.

What you can do is increase the touch area by using the `hitSlop` property eg:

```
                        <TouchableOpacity
                            hitSlop={{ top: 30, right: 30, bottom: 30, left: 30 }}
                        >
                        </TouchableOpacity>
```

Also, the touch area still will be small IMO. Allow users to select the radio button by touching on the description/title of the radio button...

Ty for the lib! 😘

**Comment by ThakurBallary** [comment]
`Allow users to select the radio button by touching on the description/title of the radio button`
It's already available. Here is the [Snack Example](https://snack.expo.dev/@thakurballary/rnrbg67)
