### ISSUE TITLE
No buttons should be selected initially

### ISSUE THREAD

**Issue by bbeckk** [ThakurBallary/react-native-radio-buttons-group#7]
Here the first item is initially selected by default. How can I make all the radio buttons unselected for the first time?

**Comment by saggiyogesh** [comment]
@ThakurBallary any update on this please.

**Comment by codetestmg** [comment]
initial="" will unselected by default

**Comment by ThakurBallary** [comment]
Fixed in [v2.0.0](https://github.com/ThakurBallary/react-native-radio-buttons-group/releases/tag/v2.0)
