### ISSUE TITLE
borderColor and color Props are not working

### ISSUE THREAD

**Issue by himanshu-0410** [ThakurBallary/react-native-radio-buttons-group#76]
I've added the component in my React Native project, facing issues with the props "borderColor" and "color". It's giving me the following error:
Type '{ radioButtons: { id: string; label: string; value: string; }[]; onPress: (id: string) => void; selectedId: string | undefined; borderColor: string; }' is not assignable to type 'IntrinsicAttributes & RadioGroupProps'.
Property 'borderColor' does not exist on type 'IntrinsicAttributes & RadioGroupProps'.

Please check the attached image and let me know if I'm doing anything wrong.
<img width="686" alt="image" src="https://github.com/ThakurBallary/react-native-radio-buttons-group/assets/166106384/5ae5e606-a2ec-4345-bf4d-0db47d684fc8">

**Comment by rafael-vitor** [comment]
@himanshu-0410 `borderColor` and `color` are props for `RadioButton` and not `RadioGroup`. 
 Add those to your `radioButtonsFormatted` objects and they'll be passed to the `RadioButton` Components underneath
