### ISSUE TITLE
Styling the button itself

### ISSUE THREAD

**Issue by XavegX367** [ThakurBallary/react-native-radio-buttons-group#78]
I would like to change the normal rounded radiobuttons to look like checkmarks (See screenshot)

<img width="112" alt="image" src="https://github.com/ThakurBallary/react-native-radio-buttons-group/assets/76949970/0ebd9592-6dac-4565-a200-58b52c1169e4">

At the moment it is:
<img width="47" alt="image" src="https://github.com/ThakurBallary/react-native-radio-buttons-group/assets/76949970/7a62516d-1807-43ca-abe0-b9510df38425">

How can I achieve this? Thanks :)

**Comment by ThakurBallary** [comment]
What you need is Checkbox and this package is for Radio Buttons.
I remember similar question in [closed issues](https://github.com/ThakurBallary/react-native-radio-buttons-group/issues/48#issuecomment-1370877206). Please take a look.
